### ISSUE TITLE
min validator string? 

### ISSUE THREAD

**Issue by meaku** [peerigon/alamid-schema#23]
@flootr can you check if min works with strings?

**Comment by flootr** [comment]
Currently `min` and `max` validators cannot be applied to String types.

Quick workaround: use a custom validator:
```javascript
function minLength(min) {
    return function minLength() {
        if (arguments[0].length < min) {
            return "minLength"
        }

        return true;
    }
}
```

I think we should provide validators for String types eventually.

**Comment by flootr** [comment]
As mentioned by @jhnns the `length` validators should be applicable to Arrays too. Actually they are, but we should change the internal naming then. I will update code & docs soon.
